(function(){
"use strict";
const embedded = !!document.getElementById("integrated-portal");
const portalRoot = document.getElementById("integrated-portal") || document;
const API = location.port === '8000' ? 'http://localhost:5134/api' : '/api';
const $ = s => portalRoot.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me, current = 'tasks', records = [], people = [], programs = [], mentors = [], accounts = [], editing = null, saveHandler;
const fields = {
 title:['Tiêu đề','text'],detail:['Nội dung / nhận xét','textarea'],profileId:['Thực tập sinh','people'],programId:['Chương trình','programs'],mentorId:['Mentor','mentors'],department:['Phòng ban','text'],start:['Bắt đầu / kỳ áp dụng','datetime-local'],end:['Kết thúc / hạn hoàn thành','datetime-local'],amount:['Số tiền (VND)','number'],capacity:['Chỉ tiêu','number'],progress:['Điểm thái độ (0–10)','number']
};
const modules = {
 programs:['Chương trình',['title','department','capacity','start','end','detail'],'Tạo chương trình theo phòng ban, chỉ tiêu và thời gian.'],
 mentors:['Mentor',['title','department','capacity','amount','detail'],'Liên kết tài khoản Mentor với phòng ban và giới hạn số người hướng dẫn.'],
 assignments:['Phân công',['title','profileId','programId','mentorId','detail'],'Mỗi thực tập sinh có một phân công đang áp dụng.'],
 tasks:['Công việc',['title','profileId','end','detail'],'Giao nhiệm vụ và cập nhật tiến độ từ 0 đến 100%.'],
 reports:['Báo cáo tuần',['title','profileId','start','detail'],'Chọn thứ Hai đầu tuần. Có thể đính kèm minh chứng sau khi lưu.'],
 evaluations:['Đánh giá',['title','profileId','detail'],'Chấm điểm theo tiêu chí; mỗi tiêu chí lưu điểm và nhận xét riêng.'],
 shifts:['Lịch làm việc',['title','profileId','start','end','detail'],'Tạo ca làm theo từng thực tập sinh; hệ thống kiểm tra trùng lịch.'],
 attendance:['Chấm công',[],'Check-in và check-out theo ngày, giờ máy chủ.'],
 leave:['Nghỉ phép',['title','profileId','start','end','detail'],'Đăng ký thời gian nghỉ, theo dõi kết quả xét duyệt.'],
 allowances:['Phụ cấp',['title','profileId','start','amount','detail'],'Quản lý phụ cấp và lịch sử thanh toán theo kỳ.'],
 support:['Yêu cầu hỗ trợ',['title','profileId','detail'],'Gửi yêu cầu và theo dõi phản hồi của HR.'],
 meetings:['Lịch họp',['title','profileId','start','end','detail'],'Tạo lịch họp và xếp email thông báo vào hàng đợi gửi.'],
 notifications:['Thông báo',[],'Thông báo về lịch, công việc và kết quả xử lý.'],
 statistics:['Thống kê',[],'Tổng hợp thực tập, chuyên cần, đánh giá và tải báo cáo.'],
 accounts:['Tài khoản',[],'Quản lý tài khoản HR, Mentor và quản trị viên.'],
 audit:['Nhật ký',[],'Nhật ký thao tác do máy chủ ghi lại.'],
 mail:['Email',[],'Email được gửi khi máy chủ có cấu hình SMTP; trạng thái Queued nghĩa là chưa gửi.'],
 backups:['Sao lưu',[],'Tạo và tải bản sao lưu được mã hóa.'],
 integrations:['Tích hợp',[],'Nhập dữ liệu HRM và sự kiện QR/thẻ theo định dạng kết nối.']
};
async function api(path, options={}) { const r = await fetch(API+path,{credentials:'include',...options}); if(!r.ok){let p=await r.json().catch(()=>null);throw new Error(p?.message||p?.detail||(r.status===401?'Phiên đăng nhập hết hạn. Hãy đăng nhập lại.':`Yêu cầu thất bại (${r.status}).`));}return r.status===204?null:r.json().catch(()=>null); }
function json(method,data){return {method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)};}
function message(text){$('#message').textContent=text;}
function button(label,fn,secondary=false){const b=document.createElement('button');b.textContent=label;if(secondary)b.className='secondary';b.onclick=()=>Promise.resolve().then(fn).catch(e=>message(e.message));return b;}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function cell(v){return `<td>${esc(v)}</td>`;}
function name(id){return people.find(x=>x.id===id)?.name||id||'';}
function date(v){return v?new Date(v).toLocaleString('vi-VN'):'';}
function manager(){return ['HR','Admin'].includes(me.role);}
function canCreate(){if(['statistics','audit','mail','backups','integrations','notifications','attendance'].includes(current))return false;if(current==='accounts')return me.role==='Admin';return manager()||(me.role==='Mentor'?['tasks','evaluations','meetings']:['reports','leave','support']).includes(current);}
async function session(){try{me=await api('/auth/me');}catch{if(embedded || (!location.search.includes('setup=') && !location.search.includes('verify=') && !location.search.includes('activate=')))location.replace('dang-nhap.html');return;}if(!embedded){location.replace(me.role==='Intern'?'thuc-tap-sinh.html':me.role==='Mentor'?'mentor.html':'hr.html');return;}$('#auth').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#identity').textContent=`${me.name} · ${me.role}`;if(me.role==='Intern')localStorage.setItem('career-portal-intern-profile-id',me.id);people=await api('/people');programs=await api('/work/programs');mentors=await api('/work/mentors');if(manager())accounts=await api('/accounts');
 const allowed=me.role==='Admin'?Object.keys(modules):me.role==='HR'?Object.keys(modules).filter(k=>!['accounts','audit','mail','backups','integrations'].includes(k)):me.role==='Mentor'?['assignments','tasks','reports','evaluations','shifts','attendance','meetings']:['programs','assignments','tasks','reports','evaluations','shifts','attendance','leave','allowances','support','meetings','notifications'];
 $('#nav').replaceChildren();for(const k of allowed)$('#nav').append(button(modules[k][0],()=>show(k)));const link=document.createElement('a');link.textContent='Hồ sơ và tài liệu';link.href=manager()?'hr.html':'thuc-tap-sinh.html';if(me.role!=='Mentor')$('#nav').append(link);await show(allowed[0]);document.dispatchEvent(new CustomEvent('portal-ready',{detail:{me,allowed,show}}));}
async function show(kind){current=kind;$('#title').textContent=modules[kind][0];$('#description').textContent=modules[kind][2];$('#create').hidden=!canCreate();$('#toolbar').replaceChildren();$('#content').replaceChildren();[...$('#nav').children].forEach(b=>b.classList.toggle('active',b.textContent===modules[kind][0]));
 if(kind==='assignments'){programs=await api('/work/programs');mentors=await api('/work/mentors');people=await api('/people');}
 if(kind==='mentors'&&manager())accounts=await api('/accounts');
 if(kind==='accounts'&&me.role==='Admin')$('#toolbar').append(button('Tài khoản thực tập sinh',internAccountEditor));
 if(kind==='backups'&&me.role==='Admin')$('#toolbar').append(button('Phục hồi vào database mới',restoreEditor));
 if(kind==='notifications'&&me.role==='Intern')$('#toolbar').append(button('Gửi lại email xác thực',async()=>{await api('/auth/resend-verification',{method:'POST'});message('Đã xếp email xác thực vào hàng đợi.');}));
 if(kind==='statistics')return statistics();if(kind==='integrations')return integrations();
 if(kind==='accounts'){accounts=await api('/accounts');records=accounts;$('#content').innerHTML=table(['Tên','Email','Vai trò','Hồ sơ liên kết','Trạng thái','Quyền','Thao tác'],accounts.map(a=>`<tr>${cell(a.name)}${cell(a.email)}${cell(a.role)}${cell(a.profileName?`${a.profileName} · ${a.studentId}`:'—')}${cell(a.activationPending?'Chờ kích hoạt':a.active?'Hoạt động':'Đã khóa')}${cell(a.permissions||'Mặc định theo vai trò')}<td><button data-edit="${a.id}">Sửa</button>${!a.emailVerifiedAt?` <button class="secondary" data-activation="${a.id}">Gửi lại kích hoạt</button>`:''}${a.id!==me.id?` <button class="secondary" data-delete="${a.id}">Xóa/khóa</button>`:''}</td></tr>`));$('#content').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>accountEditor(accounts.find(a=>a.id===+b.dataset.edit)));$('#content').querySelectorAll('[data-activation]').forEach(b=>b.onclick=async()=>{await api(`/accounts/${b.dataset.activation}/resend-activation`,{method:'POST'});message('Đã xếp email kích hoạt mới vào hàng đợi.');await show('accounts');});$('#content').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const a=accounts.find(x=>x.id===+b.dataset.delete);if(!a||!confirm(`Khóa tài khoản ${a.email}? Dữ liệu liên quan sẽ được giữ lại.`))return;await api(`/accounts/${a.id}`,{method:'DELETE'});message('Đã khóa tài khoản.');await show('accounts');});return;}
 if(kind==='backups'){let list=await api('/admin/backups');$('#toolbar').append(button('Tạo bản sao lưu',async()=>{await api('/admin/backups',{method:'POST'});await show(current);message('Đã tạo và kiểm tra giải mã bản sao lưu.');}));$('#content').innerHTML=list.length?table(['Bản sao lưu'],list.map(n=>`<tr><td><a href="${API}/admin/backups/${encodeURIComponent(n)}">${esc(n)}</a></td></tr>`)):'<p class="empty">Chưa có bản sao lưu.</p>';return;}
 if(kind==='audit'||kind==='mail'){let list=await api(kind==='audit'?'/admin/audit':'/admin/mail');let cols=kind==='audit'?['at','actor','action','resource','statusCode']:['recipient','subject','status','attempts','error'];$('#content').innerHTML=table(kind==='audit'?['Thời gian','Người thao tác','Thao tác','Tài nguyên','Kết quả']:['Người nhận','Tiêu đề','Trạng thái','Số lần thử','Lỗi'],list.map(r=>`<tr>${cols.map(k=>cell(k==='at'?date(r[k]):r[k])).join('')}</tr>`));if(kind==='mail')for(const r of list.filter(x=>x.status==='Failed'))$('#toolbar').append(button(`Thử lại email #${r.id}`,async()=>{await api(`/admin/mail/${r.id}/retry`,{method:'POST'});await show(current);}));return;}
 records=await api('/work/'+kind);if(kind==='evaluations')records=await Promise.all(records.map(async r=>({...r,scorecard:await api(`/evaluations/${r.id}/scores`)})));
 if(kind==='attendance'&&me.role==='Intern')for(const [a,t] of [['check-in','Check-in'],['check-out','Check-out']])$('#toolbar').append(button(t,async()=>{await api('/attendance/'+a,{method:'POST'});await show(current);}));
 const search=document.createElement('input');search.placeholder='Tìm tiêu đề hoặc tên thực tập sinh';search.setAttribute('aria-label','Tìm kiếm');search.oninput=()=>renderRows(records.filter(r=>(r.title+' '+name(r.profileId)).toLocaleLowerCase().includes(search.value.toLocaleLowerCase())));$('#toolbar').append(search);renderRows(records);
}
function renderRows(list){if(!list.length){$('#content').innerHTML='<p class="empty">Chưa có dữ liệu phù hợp.</p>';return;}$('#content').innerHTML=table(['Tiêu đề','Thực tập sinh / phòng ban','Thời gian','Kết quả','Thao tác'],list.map(r=>`<tr>${cell(r.title)}${cell(name(r.profileId)||r.department)}${cell([date(r.start),date(r.end)].filter(Boolean).join('\n'))}${cell(current==='tasks'?`${r.progress}% · ${r.status}`:current==='allowances'?`${r.amount.toLocaleString('vi-VN')} VND · ${r.status}`:current==='evaluations'?(r.scorecard||[]).map(s=>`${s.name}: ${s.score??'—'}/${s.maxScore}`).join(' · ')||'Chưa chấm':r.status)}<td data-id="${r.id}"></td></tr>`));for(const td of $('#content').querySelectorAll('[data-id]')){let r=list.find(x=>x.id===+td.dataset.id);td.append(button('Chi tiết',()=>detail(r),true));if(canCreate())td.append(button('Sửa',()=>edit(r),true));if(current==='evaluations'&&canCreate())td.append(button('Chấm tiêu chí',()=>evaluationScoreEditor(r)));if(current==='tasks')td.append(button('Tiến độ',()=>actionEditor(r,'progress')));if(current==='reports'&&(manager()||me.role==='Mentor'))td.append(button('Phản hồi',()=>actionEditor(r,'feedback')));if(['leave','support'].includes(current)&&manager())for(const [a,l]of [['approve','Duyệt'],['reject','Từ chối'],['close','Đóng']])td.append(button(l,()=>actionEditor(r,a)));if(current==='allowances'&&manager()&&r.status!=='Đã thanh toán')td.append(button('Đã thanh toán',()=>act(r,'paid')));if(current==='notifications'&&me.role==='Intern'&&r.status!=='Đã đọc')td.append(button('Đánh dấu đã đọc',()=>act(r,'read')));if(['reports','support'].includes(current)&&canCreate())td.append(button('Đính kèm',()=>upload(r)));}}
function openDialog(title,html,handler){$('#edit-title').textContent=title;$('#fields').innerHTML=html;$('#form-error').textContent='';$('#save').hidden=!handler;saveHandler=handler;$('#editor').showModal();}
function field(key,value){let [label,type]=fields[key];if(current==='mentors'&&key==='amount')label='Sức chứa mentor';if(current==='mentors'&&key==='capacity'){label='Tài khoản Mentor';type='accounts';}if(current==='evaluations'&&key==='amount')label='Điểm kỹ năng (0–10)';if(me.role==='Intern'&&key==='profileId')return '';const lists={people,programs,mentors,accounts:accounts.filter(x=>x.role==='Mentor'&&x.active)};let input;if(lists[type])input=`<select name="${key}" required><option value="">Chọn...</option>${lists[type].map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.name||x.title)}</option>`).join('')}</select>`;else if(type==='textarea')input=`<textarea name="${key}">${esc(value)}</textarea>`;else{let v=value;if(type==='datetime-local'&&v){let d=new Date(v);d=new Date(d.getTime()-d.getTimezoneOffset()*60000);v=d.toISOString().slice(0,16);}input=`<input name="${key}" type="${type}" value="${esc(v)}" ${type==='number'?'step="0.01" min="0"':''} ${['title','department','start','end','amount','capacity'].includes(key)?'required':''}>`;}return `<label class="${type==='textarea'?'wide':''}">${esc(label)}${input}</label>`;}
function edit(row=null){editing=row;openDialog((row?'Cập nhật ':'Thêm ')+modules[current][0],modules[current][1].map(k=>field(k,row?.[k]??'')).join(''),async form=>{let data={...(row||{})};for(const[k,v]of new FormData(form)){data[k]=['profileId','programId','mentorId','amount','capacity','progress'].includes(k)?Number(v):['start','end'].includes(k)?(v?new Date(v).toISOString():null):v;}if(me.role==='Intern')data.profileId=me.id;const route=current==='tasks'&&!row?'/tasks':current==='reports'&&!row?'/reports/weekly':'/work/'+current+(row?'/'+row.id:'');const saved=await api(route,json(row?'PUT':'POST',data));if(current==='evaluations')return {evaluation:saved};await show(current);});}
async function evaluationScoreEditor(row){const scores=await api(`/evaluations/${row.id}/scores`);const html=scores.map(s=>`<div class="wide"><strong>${esc(s.name)} · tối đa ${s.maxScore}</strong><label>Điểm<input name="score-${s.criterionId}" type="number" min="0" max="${s.maxScore}" step="0.01" value="${s.score??''}" required></label><label class="wide">Nhận xét<textarea name="comment-${s.criterionId}" maxlength="2000">${esc(s.comment)}</textarea></label></div>`).join('');openDialog('Điểm và nhận xét theo tiêu chí',html,async form=>{const data=scores.map(s=>({criterionId:s.criterionId,score:Number(form.elements[`score-${s.criterionId}`].value),comment:form.elements[`comment-${s.criterionId}`].value}));await api(`/evaluations/${row.id}/scores`,json('PUT',data));await show('evaluations');});}
function detail(r){openDialog(r.title,`<div class="wide detail">${esc(r.detail)}\n${esc(r.feedback)}\n${esc(r.history)}</div>${r.fileName?`<a href="${API}/work/${current}/${r.id}/attachment">${esc(r.fileName)}</a>`:''}`,null);}
async function act(r,a,p={}){await api(`/work/${current}/${r.id}/action`,json('POST',{action:a,...p}));await show(current);}
function actionEditor(r,a){openDialog(r.title,a==='progress'?`<label>Tiến độ (%)<input name="progress" type="number" min="0" max="100" value="${r.progress}" required></label>`:'<label class="wide">Nội dung phản hồi / lý do<textarea name="feedback" required></textarea></label>',async f=>{let d=Object.fromEntries(new FormData(f));if(d.progress)d.progress=Number(d.progress);await act(r,a,d);});}
function upload(r){openDialog('Đính kèm minh chứng','<label class="wide">PDF, DOC, DOCX, PNG, JPG — tối đa 10 MB<input name="file" type="file" accept=".pdf,.doc,.docx,.png,.jpg" required></label>',async f=>{let file=f.elements.file.files[0];if(file.size>10*1024*1024)throw Error('Tệp vượt quá 10 MB.');await api(`/work/${current}/${r.id}/attachment?fileName=${encodeURIComponent(file.name)}`,{method:'POST',body:file});await show(current);});}
function accountEditor(a=null){const available=people.filter(p=>!accounts.some(x=>x.internProfileId===p.id&&x.id!==a?.id));openDialog(a?'Sửa tài khoản':'Tạo tài khoản',`<label>Tên<input name="name" value="${esc(a?.name)}" required></label><label>Email<input name="email" type="email" value="${esc(a?.email)}" required></label><label>Vai trò<select name="role">${['HR','Mentor','Intern','Admin'].map(r=>`<option ${a?.role===r?'selected':''}>${r}</option>`).join('')}</select></label><label id="intern-profile-field">Hồ sơ thực tập sinh<select name="internProfileId"><option value="">Chọn hồ sơ...</option>${available.map(p=>`<option value="${p.id}" ${p.id===a?.internProfileId?'selected':''}>${esc(p.name)} · ${esc(p.studentId)}</option>`).join('')}</select></label><p class="wide">Mật khẩu không được gửi qua quản trị viên. Tài khoản mới nhận liên kết email dùng một lần để tự đặt mật khẩu.</p><label>Hoạt động<select name="active"><option value="true" ${a?.active!==false?'selected':''}>Có</option><option value="false" ${a?.active===false?'selected':''}>Khóa</option></select></label><label>Quyền ghi nghiệp vụ (để trống: mặc định)<input name="permissions" value="${esc(a?.permissions)}" placeholder="tasks,evaluations,meetings"></label>`,async f=>{let data=Object.fromEntries(new FormData(f));data.active=data.active==='true';data.internProfileId=data.role==='Intern'&&data.internProfileId?Number(data.internProfileId):null;await api('/accounts'+(a?'/'+a.id:''),json(a?'PUT':'POST',data));await show('accounts');message(a?'Đã cập nhật tài khoản.':'Đã tạo tài khoản và xếp email kích hoạt vào hàng đợi.');});const role=$('#fields').querySelector('[name="role"]'),profileField=$('#intern-profile-field'),profileSelect=$('#fields').querySelector('[name="internProfileId"]'),nameField=$('#fields').querySelector('[name="name"]'),emailField=$('#fields').querySelector('[name="email"]');function toggleProfile(){const isIntern=role.value==='Intern';profileField.hidden=!isIntern;profileSelect.required=isIntern;if(!isIntern)profileSelect.value='';}profileSelect.onchange=()=>{const p=people.find(x=>x.id===Number(profileSelect.value));if(p){nameField.value=p.name;emailField.value=p.email;}};role.onchange=toggleProfile;toggleProfile();}
async function statistics(){let school=document.createElement('input'),major=document.createElement('input');school.placeholder='Lọc trường';major.placeholder='Lọc ngành';school.setAttribute('aria-label','Trường');major.setAttribute('aria-label','Ngành');$('#toolbar').append(school,major);let query='';async function load(){query='?school='+encodeURIComponent(school.value)+'&major='+encodeURIComponent(major.value);let s=await api('/reports/summary'+query);$('#content').innerHTML=`<div class="cards"><div class="card">Thực tập sinh<b>${s.total}</b></div><div class="card">Đã hoàn thành<b>${s.completed}</b></div><div class="card">Tỷ lệ hoàn thành<b>${s.completionRate}%</b></div></div><h2>Trường và ngành</h2>`+table(['Trường','Ngành','Số lượng'],s.schools.map(x=>`<tr>${cell(x.school)}${cell(x.major)}${cell(x.count)}</tr>`))+'<h2>Khối lượng hướng dẫn</h2>'+table(['Mentor','Được phân công','Sức chứa'],s.mentors.map(x=>`<tr>${cell(x.title)}${cell(x.assigned)}${cell(x.capacity)}</tr>`))+'<h2>Chuyên cần</h2>'+table(['Họ tên','Lượt chấm công','Giờ làm','Đơn nghỉ đã duyệt'],s.attendance.map(x=>`<tr>${cell(x.name)}${cell(x.days)}${cell(x.hours)}${cell(x.leave)}</tr>`))+'<h2>Đánh giá cuối kỳ</h2>'+table(['Thực tập sinh','Kỹ năng','Thái độ','Nhận xét'],s.evaluations.map(x=>`<tr>${cell(name(x.profileId))}${cell(x.skill)}${cell(x.attitude)}${cell(x.detail)}</tr>`));}$('#toolbar').append(button('Áp dụng',load),button('Xuất Excel',()=>location.assign(API+'/reports/export.xlsx'+query)),button('In / lưu PDF',()=>window.print()));await load();}
function integrations(){const samples={hrm:[{employeeCode:'NV001',name:'Nguyễn Văn A',email:'a@example.test',school:'ICTU',major:'CNTT'}],attendance:{eventId:'device-001',studentId:'HRM-NV001',start:new Date().toISOString(),end:null}};for(const k of ['hrm','attendance'])$('#toolbar').append(button(k==='hrm'?'Nhập HRM':'Nhập sự kiện QR/thẻ',()=>openDialog(k==='hrm'?'Đồng bộ nhân sự':'Sự kiện chấm công',`<label class="wide">Dữ liệu JSON<textarea name="payload" rows="12" required>${esc(JSON.stringify(samples[k],null,2))}</textarea></label>`,async f=>{let result=await api('/admin/integrations/'+k,json('POST',JSON.parse(f.elements.payload.value)));message(JSON.stringify(result));})));$('#content').innerHTML='<p class="detail">Điểm kết nối nhận dữ liệu từ HRM hoặc thiết bị thông qua tài khoản Admin. Mã nhân sự / mã sự kiện được dùng chống nhập trùng. Cần adapter của nhà cung cấp để tự động đẩy dữ liệu từ hệ thống thực tế.</p>';}
$('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api(f.get('role')==='Intern'?'/interns/login':'/auth/login',json('POST',{identity:f.get('identity'),password:f.get('password')}));await session();message('Đăng nhập thành công.');}catch(e){message(e.message);}};
$('#register').onsubmit=async e=>{e.preventDefault();try{await api('/interns/register',json('POST',Object.fromEntries(new FormData(e.target))));message('Đăng ký thành công. Hãy đăng nhập bằng tài khoản vừa tạo.');e.target.reset();}catch(e){message(e.message);}};
$('#bootstrap').onsubmit=async e=>{e.preventDefault();try{let d=Object.fromEntries(new FormData(e.target));let opt=json('POST',{...d,role:'Admin'});opt.headers['X-Bootstrap-Token']=d.token;await api('/auth/bootstrap',opt);message('Đã tạo quản trị viên. Chọn đăng nhập HR / Mentor / Quản trị viên.');e.target.reset();}catch(e){message(e.message);}};
$('#logout').onclick=async()=>{await api('/auth/logout',{method:'POST'});localStorage.removeItem('career-portal-intern-profile-id');location.reload();};$('#create').onclick=()=>current==='accounts'?accountEditor():edit();$('#cancel').onclick=()=>$('#editor').close();$('#edit-form').onsubmit=async e=>{e.preventDefault();if(!saveHandler)return;$('#save').disabled=true;try{const next=await saveHandler(e.target);$('#editor').close();if(next?.evaluation)await evaluationScoreEditor(next.evaluation);}catch(e){$('#form-error').textContent=e.message;}finally{$('#save').disabled=false;}};
async function internAccountEditor(){people=await api('/people');openDialog('Gửi kích hoạt hoặc khóa tài khoản thực tập sinh',`<label>Thực tập sinh<select name="id" required>${people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><p class="wide">Thực tập sinh sẽ nhận liên kết dùng một lần để tự đặt mật khẩu. Không gửi mật khẩu ban đầu qua email.</p><label>Trạng thái<select name="active"><option value="true">Hoạt động</option><option value="false">Khóa</option></select></label>`,async f=>{let d=Object.fromEntries(new FormData(f));await api(`/admin/interns/${d.id}/account`,json('POST',{password:'',active:d.active==='true'}));message(d.active==='true'?'Đã xếp email kích hoạt vào hàng đợi nếu tài khoản chưa được xác thực.':'Đã khóa tài khoản thực tập sinh.');});}
async function restoreEditor(){let files=await api('/admin/backups');openDialog('Phục hồi dữ liệu vào database mới',`<p class="wide">Tạo một database mới từ bản sao lưu. Database hiện tại được giữ nguyên. Tên database phục hồi sẽ được hiển thị sau khi hoàn tất.</p><label class="wide">Bản sao lưu<select name="file" required>${files.map(f=>`<option>${esc(f)}</option>`).join('')}</select></label>`,async f=>{let r=await api('/admin/backups/'+encodeURIComponent(f.elements.file.value)+'/restore',{method:'POST'});message('Đã phục hồi: '+r.database);});}
const verificationQuery = new URLSearchParams(location.search);
if(verificationQuery.has('verify'))api('/auth/verify-email',json('POST',{profileId:Number(verificationQuery.get('profileId')),token:verificationQuery.get('verify')})).then(()=>{message('Email đã được xác thực. Bạn có thể đăng nhập và nộp hồ sơ.');history.replaceState(null,'','index.html');}).catch(e=>message(e.message));
if(verificationQuery.has('activate')){
 const activationToken=verificationQuery.get('activate');history.replaceState(null,'','index.html');
 $('#auth').hidden=true;$('#workspace').hidden=true;$('#logout').hidden=true;
 const panel=document.createElement('main');panel.style.cssText='max-width:460px;margin:8vh auto;padding:28px;border:1px solid #d7dce2;border-radius:12px;background:#fff;font:16px system-ui,sans-serif;color:#17212b;box-shadow:0 8px 28px #0001';
 panel.innerHTML='<h1 style="font-size:24px;margin-top:0">Kích hoạt tài khoản</h1><p>Đặt mật khẩu mới để hoàn tất kích hoạt. Mật khẩu cần có ít nhất 12 ký tự.</p><form><label style="display:block;margin:16px 0">Mật khẩu mới<input name="password" type="password" minlength="12" maxlength="200" autocomplete="new-password" required style="display:block;width:100%;box-sizing:border-box;padding:10px;margin-top:6px"></label><label style="display:block;margin:16px 0">Nhập lại mật khẩu<input name="confirm" type="password" minlength="12" maxlength="200" autocomplete="new-password" required style="display:block;width:100%;box-sizing:border-box;padding:10px;margin-top:6px"></label><button type="submit" style="padding:10px 16px">Kích hoạt</button><p role="status" aria-live="polite"></p></form>';
 document.body.append(panel);const form=panel.querySelector('form'),status=form.querySelector('[role="status"]');
 form.onsubmit=async event=>{event.preventDefault();const password=form.elements.password.value;if(password!==form.elements.confirm.value){status.textContent='Hai mật khẩu chưa khớp.';return;}const submit=form.querySelector('button');submit.disabled=true;try{const result=await api('/auth/activate-account',json('POST',{token:activationToken,password}));status.textContent=result?.message||'Tài khoản đã được kích hoạt.';form.querySelectorAll('label,button').forEach(x=>x.hidden=true);const link=document.createElement('a');link.href='dang-nhap.html';link.textContent='Đăng nhập';panel.append(link);}catch(error){status.textContent=error.message+' Hãy liên hệ quản trị viên để gửi lại email kích hoạt.';submit.disabled=false;}};
}else session().catch(e=>message(e.message));

})();
