using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
var builder=WebApplication.CreateBuilder(args);
builder.Services.AddValidation();
builder.Services.AddOpenApi();
builder.Services.AddDbContext<CareerDbContext>(o=>o.UseSqlServer(builder.Configuration.GetConnectionString("CareerPortal")));
builder.Services.AddScoped<IPasswordHasher<InternProfile>,PasswordHasher<InternProfile>>();
builder.Services.AddDataProtection().SetApplicationName("CareerPortal.Sprint1").PersistKeysToFileSystem(new DirectoryInfo(Path.Combine(builder.Environment.ContentRootPath,"App_Data","keys")));
builder.Services.AddAuthentication("Sprint1").AddCookie("Sprint1",o=>{
    o.Cookie.Name="CareerPortal.Sprint1";o.Cookie.HttpOnly=true;o.Cookie.SameSite=SameSiteMode.Strict;o.ExpireTimeSpan=TimeSpan.FromHours(8);
    o.Events.OnRedirectToLogin=c=>{c.Response.StatusCode=401;return Task.CompletedTask;};
    o.Events.OnRedirectToAccessDenied=c=>{c.Response.StatusCode=403;return Task.CompletedTask;};
});
builder.Services.AddAuthorization();builder.Services.AddHostedService<MailWorker>();builder.Services.AddHostedService<InternshipStatusWorker>();
var app=builder.Build();
app.UseAuthentication();app.UseAuthorization();app.UseMiddleware<SprintSecurity>();
var frontend=Path.GetFullPath(Path.Combine(app.Environment.ContentRootPath,"../../frontend"));
app.UseDefaultFiles(new DefaultFilesOptions{FileProvider=new Microsoft.Extensions.FileProviders.PhysicalFileProvider(frontend)});
app.UseStaticFiles(new StaticFileOptions{FileProvider=new Microsoft.Extensions.FileProviders.PhysicalFileProvider(frontend)});
app.MapSprintAuth();app.MapProfiles();app.MapDocuments();app.MapApplications();app.MapInternSchedules();
if(app.Environment.IsDevelopment())app.MapOpenApi();
app.MapGet("/api/health/database",async(CareerDbContext db)=>await db.Database.CanConnectAsync()?Results.Ok(new{connected=true}):Results.StatusCode(503));
app.Run();
