using System.ComponentModel.DataAnnotations;
public sealed class InternshipTask { public int Id { get; set; } public required string Title { get; set; } public string Description { get; set; } = ""; public DateOnly? DueDate { get; set; } public string Priority { get; set; } = "Normal"; public string Status { get; set; } = "Todo"; public int Progress { get; set; } public int MentorId { get; set; } public Mentor? Mentor { get; set; } public int ProfileId { get; set; } public InternProfile? Profile { get; set; } public int? ProgramId { get; set; } public InternshipProgram? Program { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TaskProgressHistory { public int Id { get; set; } public int TaskId { get; set; } public InternshipTask? Task { get; set; } public int Progress { get; set; } public string Status { get; set; } = "Todo"; public string? Note { get; set; } public DateTimeOffset ChangedAt { get; set; } = DateTimeOffset.UtcNow; public int ChangedByUserId { get; set; } }
public sealed class WeeklyReport { public int Id { get; set; } public int ProfileId { get; set; } public InternProfile? Profile { get; set; } public DateOnly WeekStart { get; set; } public required string Summary { get; set; } public string? Blockers { get; set; } public string? EvidenceUrl { get; set; } public string Status { get; set; } = "Submitted"; public string? MentorFeedback { get; set; } public DateTimeOffset SubmittedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? ReviewedAt { get; set; } public string? ReviewedBy { get; set; } }
public sealed record TaskInput([property:Required,MaxLength(180)] string Title, [property:MaxLength(3000)] string Description, DateOnly? DueDate, string Priority, int ProfileId, int? ProgramId);
public sealed record TaskProgressInput([property:Range(0,100)] int Progress, string Status, [property:MaxLength(1000)] string? Note);
public sealed record WeeklyReportInput(DateOnly WeekStart, [property:Required,MaxLength(6000)] string Summary, [property:MaxLength(2000)] string? Blockers, [property:MaxLength(500)] string? EvidenceUrl);
public sealed record WeeklyFeedbackInput([property:Required,MaxLength(2000)] string Feedback);
public sealed class PortalNotification { public int Id { get; set; } public int? AccountId { get; set; } public int? ProfileId { get; set; } public required string Title { get; set; } public required string Message { get; set; } public string? Link { get; set; } public bool IsRead { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class InternshipEvaluation { public int Id { get; set; } public int MentorId { get; set; } public Mentor? Mentor { get; set; } public int ProfileId { get; set; } public InternProfile? Profile { get; set; } public int? ProgramId { get; set; } public InternshipProgram? Program { get; set; } public int Skills { get; set; } public int Attitude { get; set; } public int Communication { get; set; } public int? Teamwork { get; set; } public string Comment { get; set; } = ""; public bool IsLocked { get; set; } public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed record EvaluationInput(int ProfileId,int? ProgramId,[property:Range(1,5)] int Skills,[property:Range(1,5)] int Attitude,[property:Range(1,5)] int Communication,int? Teamwork,[property:MaxLength(3000)] string Comment);
