using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
var connection=Environment.GetEnvironmentVariable("ConnectionStrings__CareerPortal")??"Server=(localdb)\\MSSQLLocalDB;Database=CareerPortalSprint1;Trusted_Connection=True;TrustServerCertificate=True";
var options=new DbContextOptionsBuilder<CareerDbContext>().UseSqlServer(connection).Options;
await using var db=new CareerDbContext(options);
var tag=Guid.NewGuid().ToString("N");var baseUrl=Environment.GetEnvironmentVariable("SPRINT1_URL")??"http://localhost:5135";
using var http=new HttpClient(new HttpClientHandler{CookieContainer=new CookieContainer()}){BaseAddress=new Uri(baseUrl)};
var missingPhone=await http.PostAsJsonAsync("/api/interns/register",new{name="Missing phone",studentId=tag+"-missing-phone",email=tag+"-missing-phone@example.test",school="DB Test",major="DB Test",password="TestOnly123!"});
if(missingPhone.StatusCode!=HttpStatusCode.BadRequest)throw new Exception("Registration accepted without phone");
var futureDate=DateOnly.FromDateTime(DateTime.Today.AddDays(1));
var futureBirthRegistration=await http.PostAsJsonAsync("/api/interns/register",new{name="Future birth date",studentId=tag+"-future",email=tag+"-future@example.test",phone=$"0{Random.Shared.NextInt64(100_000_000,1_000_000_000)}",dateOfBirth=futureDate,school="DB Test",major="DB Test",password="TestOnly123!"});
if(futureBirthRegistration.StatusCode!=HttpStatusCode.BadRequest)throw new Exception("Registration accepted a future date of birth");
using var futureBirthJson=JsonDocument.Parse(await futureBirthRegistration.Content.ReadAsStringAsync());
if(!futureBirthJson.RootElement.GetProperty("errors").TryGetProperty("DateOfBirth",out _))throw new Exception("Future date-of-birth field error missing");
if(futureBirthJson.RootElement.GetProperty("errors").GetProperty("DateOfBirth")[0].GetString()!="Ngày sinh không hợp lệ.")throw new Exception("Unexpected future date-of-birth registration message");
var phone=$"0{Random.Shared.NextInt64(100_000_000,1_000_000_000)}";
var dateOfBirth=new DateOnly(2004,5,16);
var response=await http.PostAsJsonAsync("/api/interns/register",new{name="Database test",studentId=tag,email=tag+"@example.test",phone,dateOfBirth,school="DB Test",major="DB Test",password="TestOnly123!"});response.EnsureSuccessStatusCode();
var secondPhone=$"0{Random.Shared.NextInt64(100_000_000,1_000_000_000)}";
var sharedStudent=await http.PostAsJsonAsync("/api/interns/register",new{name="Second database test",studentId=tag,email=tag+"-second@example.test",phone=secondPhone,school="DB Test",major="DB Test",password="TestOnly123!"});sharedStudent.EnsureSuccessStatusCode();
var p=await db.InternProfiles.SingleAsync(x=>x.StudentId==tag&&x.Email==tag+"@example.test");if(p.PasswordHash=="TestOnly123!"||p.PasswordHash.Length<40)throw new Exception("Password not hashed");if(p.DateOfBirth!=dateOfBirth)throw new Exception("Date of birth not persisted");
var sharedStudentLogin=await http.PostAsJsonAsync("/api/interns/login",new{identity=tag,password="TestOnly123!"});
if(sharedStudentLogin.StatusCode!=HttpStatusCode.BadRequest)throw new Exception("Student ID accepted as login identity");
var sharedStudentEmailLogin=await http.PostAsJsonAsync("/api/interns/login",new{identity=tag+"-second@example.test",password="TestOnly123!"});
sharedStudentEmailLogin.EnsureSuccessStatusCode();
var duplicateEmail=await http.PostAsJsonAsync("/api/interns/register",new{name="Duplicate email",studentId=tag+"-email",email=tag.ToUpperInvariant()+"@example.test",phone=$"0{Random.Shared.NextInt64(100_000_000,1_000_000_000)}",school="DB Test",major="DB Test",password="TestOnly123!"});
if(duplicateEmail.StatusCode!=HttpStatusCode.Conflict)throw new Exception("Duplicate email accepted");
using var duplicateEmailJson=JsonDocument.Parse(await duplicateEmail.Content.ReadAsStringAsync());
if(!duplicateEmailJson.RootElement.GetProperty("errors").TryGetProperty("Email",out _))throw new Exception("Duplicate email field error missing");
var duplicatePhone=await http.PostAsJsonAsync("/api/interns/register",new{name="Duplicate phone",studentId=tag+"-phone",email=tag+"-phone@example.test",phone="+84"+phone[1..],school="DB Test",major="DB Test",password="TestOnly123!"});
if(duplicatePhone.StatusCode!=HttpStatusCode.Conflict)throw new Exception("Equivalent Vietnamese phone accepted");
using var duplicatePhoneJson=JsonDocument.Parse(await duplicatePhone.Content.ReadAsStringAsync());
if(!duplicatePhoneJson.RootElement.GetProperty("errors").TryGetProperty("Phone",out _))throw new Exception("Duplicate phone field error missing");
response=await http.PostAsJsonAsync("/api/interns/login",new{identity=p.Email,password="TestOnly123!"});response.EnsureSuccessStatusCode();
var futureBirthUpdate=await http.PutAsJsonAsync($"/api/interns/{p.Id}",new{name=p.Name,email=p.Email,phone=p.Phone,dateOfBirth=futureDate,school=p.School,major=p.Major});
if(futureBirthUpdate.StatusCode!=HttpStatusCode.BadRequest)throw new Exception("Profile update accepted a future date of birth");
using var futureUpdateJson=JsonDocument.Parse(await futureBirthUpdate.Content.ReadAsStringAsync());
if(!futureUpdateJson.RootElement.GetProperty("errors").TryGetProperty("DateOfBirth",out _))throw new Exception("Future date-of-birth update field error missing");
if(futureUpdateJson.RootElement.GetProperty("errors").GetProperty("DateOfBirth")[0].GetString()!="Ngày sinh không hợp lệ.")throw new Exception("Unexpected future date-of-birth update message");
await db.Entry(p).ReloadAsync();if(p.DateOfBirth!=dateOfBirth)throw new Exception("Rejected future date changed persisted date of birth");
var contract=new InternDocument{ProfileId=p.Id,Type="Hợp đồng thực tập",FileName="expired.pdf",ContentType="application/pdf",Content="%PDF-1.4\n%%EOF"u8.ToArray(),Status="Chờ xác nhận",ExpiresAt=DateTimeOffset.UtcNow.AddDays(-1),UploadedBy="TEST ONLY"};db.InternDocuments.Add(contract);await db.SaveChangesAsync();
response=await http.PostAsync($"/api/contracts/{contract.Id}/confirm",null);if(response.StatusCode!=HttpStatusCode.Conflict)throw new Exception("Expired contract accepted");
await db.Entry(contract).ReloadAsync();if(contract.ConfirmedAt!=null)throw new Exception("Expired contract mutated");
var mail=new MailJob{EventKey="retry-test:"+tag,Recipient="INVALID EMAIL",Subject="Local retry test",Body="Test only"};db.MailJobs.Add(mail);await db.SaveChangesAsync();
for(var i=0;i<15;i++){await Task.Delay(1000);await db.Entry(mail).ReloadAsync();if(mail.Attempts>0)break;}
if(mail.Attempts!=1||mail.Status!="Queued"||string.IsNullOrEmpty(mail.LastError))throw new Exception("Failure not queued/logged");
mail.Recipient=p.Email;mail.DueAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync();
for(var i=0;i<15;i++){await Task.Delay(1000);await db.Entry(mail).ReloadAsync();if(mail.Status=="Sent")break;}
if(mail.Status!="Sent"||mail.Attempts!=2)throw new Exception("Retry failed");
var entity=db.Model.FindEntityType(typeof(InternProfile))!;
foreach(var field in new[]{"School","Major","Status"})if(!entity.GetIndexes().Any(x=>x.Properties.Any(p=>p.Name==field)))throw new Exception("Missing index "+field);
Console.WriteLine("PASS: Database persistence, password hash, expired contract rejection, unchanged confirmation, failed email log, retry to Sent, school/major/status indexes.");
